Data missing error handling - battery.py
Getting errors when data missing like the following:

ERROR (MainThread) [homeassistant.components.melnor.coordinator] Unexpected error fetching Melnor Bluetooth data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melnor/coordinator.py", line 39, in _async_update_data
    await self._device.fetch_state()
  File "/usr/local/lib/python3.13/site-packages/melnor_bluetooth/device.py", line 349, in fetch_state
    self._battery = parse_battery_value(some_bytes)
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/melnor_bluetooth/utils/battery.py", line 4, in parse_battery_value
    if (bytes[0] & 255 == 238) and (bytes[1] & 255 == 238):
        ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable