Fix TypeError messages from device.py
Fix to step error messages like the following:

Unexpected error fetching Melnor Bluetooth data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/melnor/coordinator.py", line 39, in _async_update_data
    await self._device.fetch_state()
  File "/usr/local/lib/python3.13/site-packages/melnor_bluetooth/device.py", line 353, in fetch_state
    valve.update_state(bytes_array[some_bytes], uuids[i])
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/melnor_bluetooth/device.py", line 69, in update_state
    self._is_watering = struct.unpack_from(">?", raw_bytes, offset)[0]
                        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'NoneType'